name: CI

on:
  push:
    branches: [ main, coding-branch, testing-branch ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
      - name: Install dependencies
        run: |
          cd web
          npm ci
      - name: Run tests
        run: |
          cd web
          npm test
